name: Release
on:
  release:
    types: [published]
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    name: mises-sns node ${{ matrix.node-version }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and Test
        run: |
          yarn
          yarn test
          yarn build
        env:
          CI: true
      - name: 'Tar files'
        run: |
          tar -czvf sns-web.tar.gz build/ appspec.yml scripts/
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Deploy to S3
        run: |
          aws s3 cp \
           --region us-east-2 \
           sns-web.tar.gz s3://misesid
      - name: CodeDeploy to EC2
        run: |
          aws deploy create-deployment \
           --application-name sns-web \
           --deployment-group-name SnsWebDeployGroup \
           --s3-location bucket=misesid,key=sns-web.tar.gz,bundleType=tgz \
           --file-exists-behavior OVERWRITE